require "spec"
require "../src/changelog_config"
require "../src/changelog_database"
require "../src/changelog_generator"
require "../src/changelog_entry"
require "../src/changelog_entry_generator"
require "../src/git_integration"
require "../src/changelog_manager/*"
