#!/bin/bash

# outputs the list of files in .changelog_entries along with the description
# contain in each one.
# useful for finding one to edit / remove.

grep -r --color=none tags .changelog_entries/* |\
  sed -e 's/^.*tags":\[//'  -e 's/\].*//'  -e 's/"//g' \
  -e 's/^[[:space:]]*$//' -e '/^$/d' -e 's/[[:space:]]/\n/g' |\
  sort |\
  uniq |\
  tr '\n' ',' |\
  sed -e 's/,$//' -e 's/,/, /g'


